### ISSUE TITLE
Test failures: out of resources

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDAnative.jl#444] opened 2019-08-09 09:18 UTC
In each case I have made sure the required LLVM, CUDAapi, CUDAdrv pass their tests.

Error logs on the school cluster:
* [gpu=K20,cuda=9.1,cudnn=7.0.5,cudanative=2.2.1
](http://ai.ku.edu.tr/dyuret/cudanative2.2.1-sm35-cuda9.1-cudnn7.0.5.err.txt)
* [gpu=V100,cuda=9.1,cudnn=7.0.5,cudanative=2.2.1
](http://ai.ku.edu.tr/dyuret/cudanative2.2.1-sm70-cuda9.1-cudnn7.0.5.err.txt)
* [gpu=K20,cuda=10.1,cudnn=7.0.6,cudanative=2.2.1
](http://ai.ku.edu.tr/dyuret/cudanative2.2.1-sm35-cuda10.1-cudnn7.0.6.err.txt)
* [gpu=V100,cuda=10.1,cudnn=7.0.6,cudanative=2.2.1
](http://ai.ku.edu.tr/dyuret/cudanative2.2.1-sm70-cuda10.1-cudnn7.0.6.err.txt)

On AWS (AMI=Knet-1.2.3 in Ohio):
* [gpu=K80,cuda=10.0,cudnn=7.4.2,cudanative=2.2.1
](http://ai.ku.edu.tr/dyuret/cudanative2.2.1-sm37-cuda10.0-cudnn7.4.2.err.txt)

**Comment by maleadt** [comment] 2019-08-19 11:19
pairwise failures have been fixed in https://github.com/JuliaGPU/CUDAnative.jl/pull/433/commits/a8bfda6e2d56550038af0b691ae711f3d64ddb3b
can't reproduce the other issue. can you test if lowering the number of threads to, say, 256 here helps: https://github.com/JuliaGPU/CUDAnative.jl/blob/027e707c3fc6014431588bffa7d2e9699f552b6f/test/device/cuda.jl#L251

**Comment by denizyuret** [comment] 2019-08-19 15:53
I can confirm that a8bfda6 fixes the pairwise issue and n = 256 fixes the resources issue.

**Closed** 2019-08-20 06:27 UTC
