### ISSUE TITLE
Increased resource usage for pairwise example

### ISSUE THREAD

**Issue by samcmill** [JuliaGPU/CUDAnative.jl#434] opened 2019-07-16 15:37 UTC
The pairwise example fails for v2.2.0 and v2.2.1.  It works for v2.1.3.

```
$ julia -e 'using Pkg; Pkg.text("CUDAnative") 
   Testing CUDAnative
 Resolving package versions...
    Status `/tmp/tmpQXILkB/Manifest.toml`
  [79e6a3ab] Adapt v0.4.2
  [3895d2a7] CUDAapi v0.6.3
  [c5f51814] CUDAdrv v3.0.1
  [be33ccc6] CUDAnative v2.2.1
  [a8cc5b0e] Crayons v4.0.0
  [864edb3b] DataStructures v0.17.0
  [929cbde3] LLVM v1.1.1
  [bac558e1] OrderedCollections v1.1.0
  [a759f4b9] TimerOutputs v0.5.0
...
[ Info: Testing using device Quadro GP100
Error During Test at /root/.julia-ngc/packages/CUDAnative/nItlk/examples/pairwise.jl:113
  Test threw exception
  Expression: ≈(pairwise_dist_cpu(lat, lon), pairwise_dist_gpu(lat, lon), rtol=0.01)
  CUDA error: too many resources requested for launch (code #701, ERROR_LAUNCH_OUT_OF_RESOURCES)
...
Test Summary:                           | Pass  Fail  Broken  Total
CUDAnative                              |  372     1       1    374
  base interface                        |                     No tests
  pointer                               |   20                   20
  code generation                       |   89             1     90
  code generation (relying on a device) |    6                    6
  execution                             |   75                   75
  pointer                               |   41                   41
  device arrays                         |   20                   20
  CUDA functionality                    |  108                  108
  examples                              |    5     1              6
    example = hello_world.jl            |    1                    1
    example = pairwise.jl               |          1              1
    example = peakflops.jl              |    1                    1
    example = reduce/verify.jl          |    1                    1
    example = scan.jl                   |    1                    1
    example = vadd.jl                   |    1                    1
ERROR: LoadError: Some tests did not pass: 372 passed, 1 failed, 0 errored, 1 broken.
...
```

Note: I pulled in https://github.com/JuliaGPU/CUDAnative.jl/commit/b87eeabff59a51dfed4d393eec4058eb0ac11f59 to get additional test failure output.

Since the error is `ERROR_LAUNCH_OUT_OF_RESOURCES`, reducing the total number of threads in the pairwise example does workaround the issue.  In this particular configuration, the 841 (29x29) threads case was successful, while 900 (30x30) threads was not.  The unmodified example uses 10000 threads in this configuration.  This is less than `CUDAdrv.MAX_THREADS_PER_BLOCK`, so presumably the resource limit is shared memory.

Alternatively, reverting the changes to `src/compiler/driver.jl` (https://github.com/JuliaGPU/CUDAnative.jl/compare/v2.1.3...v2.2.0) resolves the failure with *no* modifications to the pairwise example.

**Comment by maleadt** [comment] 2019-07-16 15:45
Just fixed that in https://github.com/JuliaGPU/CUDAnative.jl/pull/433/commits/6bee219f1e1b99ec70f625387fa2a862573f3508 :-) It's suspicious how the resource usage went up between those two versions, so I should have a look at that.

**Comment by maleadt** [comment] 2019-07-23 20:12
Strange, the change you mention (https://github.com/JuliaGPU/CUDAnative.jl/pull/417) was intended to improve performance, since linking `libcudadevrt` (which triggers RDC compilation) had shown to significantly increase register usage on the [Oceananigans.jl](https://github.com/climate-machine/Oceananigans.jl/). Similarly, comparing the example as compiled on v2.1.3 vs v2.2.0 seems to improve performance:

```
$ git checkout v2.1.3
$ JULIA_DEBUG=CUDAnative nvprof --print-gpu-trace julia pairwise.jl

┌ Debug: Compiled pairwise_dist_kernel to PTX 7.0.0 for SM 7.5.0 using 42 registers.
│ Memory usage: 200 bytes local, 0 bytes shared, 256 bytes constant
└ @ CUDAnative ~/Julia/pkg/CUDAnative/src/execution.jl:382

==29706== Profiling application: julia pairwise.jl
==29706== Profiling result:
Regs*    SSMem*    DSMem*           Device   Context    Stream  Name
   42        0B      512B  GeForce RTX 208         1         7  ptxcall_pairwise_dist_kernel_27 [51]


$ git checkout v2.2.0
$ JULIA_DEBUG=CUDAnative nvprof --print-gpu-trace julia pairwise.jl

┌ Debug: Compiled pairwise_dist_kernel to PTX 7.0.0 for SM 7.5.0 using 42 registers.
│ Memory usage: 152 bytes local, 0 bytes shared, 0 bytes constant
└ @ CUDAnative ~/Julia/pkg/CUDAnative/src/execution.jl:390

==30160== Profiling application: julia pairwise.jl
==30160== Profiling result:
Regs*    SSMem*    DSMem*           Device   Context    Stream  Name
   42        0B      512B  GeForce RTX 208         1         7  ptxcall_pairwise_dist_kernel_27 [45]
```

So I'm not sure why you would only get the `ERROR_LAUNCH_OUT_OF_RESOURCES` on v2.2.0...

**Comment by maleadt** [comment] 2019-08-20 06:27
I've looked some more into this, but can't find (with the public tools and APIs I have access to) any increase in resources by the change in https://github.com/JuliaGPU/CUDAnative.jl/pull/417, so I'm going to close this. This specific issue I've worked around by using the occupancy API (https://github.com/JuliaGPU/CUDAnative.jl/commit/6bee219f1e1b99ec70f625387fa2a862573f3508).

**Closed by maleadt** 2019-08-20 06:27 UTC
Labels: performance
